### ISSUE TITLE
自作メッセージの型変換ができない

### ISSUE THREAD

**Issue by qoopen0815** [Field-Robotics-Japan/unit04_unity#2]
## 作業環境

- OS : windows10
- Unity version : 2019.3.10f1
- branch : dev/add_velodyne

## 症状
表題の通りです。
現在、ROS#で自作したROSのvelodyne_msgsを用いて、
仮想環境内で取得したLidarのデータをROS側にpublishするスクリプトを書いています。

[サンプル](https://github.com/Field-Robotics-Japan/unit04_unity/blob/dev/add_velodyne/Assets/Scripts/VelodyneLidarUnity/Velodyne_UDP_Send.cs)をもとに、シリアライズされたデータをvelodyne_msgs/VelodyneScan型に格納してpublishしたいのですが、byte[]からvelodyne_msgs/VelodyneScan型への変換がうまいこといかずに苦戦しています。[here](https://github.com/Field-Robotics-Japan/unit04_unity/blob/fd5a1335d5987073b8f29caa7b10f412849f5e17/Assets/Scripts/VelodyneLidarUnity/VelodynePublisher.cs#L116)
対策などあれば教えていただきたいです。

**Comment by qoopen0815** [comment]
自作した型は下記に保存してあります。
https://github.com/Field-Robotics-Japan/unit04_unity/tree/dev/add_velodyne/Assets/RosSharpMessages

これをvisual studioでビルドしてでてきたバイナリデータRosBridgeClient.dllをAssets/RosSharp/Plugin/にコピーすることで、自作したメッセージを追加してます。

**Comment by RyodoTanaka** [comment]
`packet.data` にシリアライズした情報が入っているようなので，
`message.packets = packet.data;`
としたらどうですか？

**Comment by qoopen0815** [comment]
>packet.data にシリアライズした情報が入っているようなので，
message.packets = packet.data;
としたらどうですか？

そうしたところ、
```型 'byte[]' を 'RosSharp.RosBridgeClient.MessageTypes.Velodyne.VelodynePacket[]' に暗黙的に変換できません [Assembly-CSharp]csharp(CS0029)```
となってしまいます。

原因は
VelodyneScanに含まれるVelodynePacket[]がuint8[]との互換を持ってないから
ではないかと考えています。

ROSではVelodyneScan内のVelodynePacket[]がvelodyne_msgs/VelodynePacketに結びついているので、VelodynePacket内のuint8との互換があると思うのですが、自作したメッセージだとそうなっていないようです。

**Comment by RyodoTanaka** [comment]
今手元でやってみていました
同じエラーが出ています．

環境は
OS : Ubuntu 18.04 LTS
Unity : 2019.3.10f

**Comment by qoopen0815** [comment]
あ、すいません。
これ勘違いでした。

VelodyneScan内のVelodynePachetは、正しくはVelodynePacket[]、つまり配列で定義してました、、、

**Comment by RyodoTanaka** [comment]
うん
今確認して，追加する方法やってみてます！

**Comment by RyodoTanaka** [comment]
ひとまずこの話題は解決したので閉じます．
